# Generated by Django 5.0.6 on 2024-05-11 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="head",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="event",
            name="desc",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="hall_of_fame",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="hall_of_fame",
            name="contact",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="hall_of_fame",
            name="designation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="hall_of_fame",
            name="pic",
            field=models.ImageField(blank=True, upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
