# Generated by Django 5.0.6 on 2024-05-11 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0002_club_head_event_desc_hall_of_fame_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.TextField()),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("experience", models.CharField(max_length=100)),
                ("date_added", models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
