# Generated by Django 5.0.6 on 2024-05-17 18:12

import features.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0008_alter_resources_file_alter_resources_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="file",
            field=models.FileField(
                blank=True,
                default=features.models.default_file_path,
                upload_to="resources/",
            ),
        ),
    ]
